# configuration for the stackbrew.tmpl template
variants:
  - dir: alpine
    tags: [ v2.0.0-beta.13, v2.0.0-beta.13-alpine, alpine, latest ]
    architectures: [ amd64 ]
  - dir: scratch
    tags: [ v2.0.0-beta.13-slim, scratch]
    architectures: [ amd64 ]
